import Navbar from '@/components/Navbar'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import AuthProvider from './auth/Provider'
import './globals.css'
import GoogleAnalyticsScript from './GoogleAnalyticsScript'

const inter = Inter({ subsets: ['latin'] })

// const roboto = Roboto({ subsets: ['latin'], weight: ['400', '700'] })

// const localFonts = localFont({
//     src: '../public/fonts/Inter-VariableFont_slnt,wght.ttf',
//     variable: '--font-inter',
// })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    openGraph: {
        title: 'Create Next App',
        description: 'Generated by create next app',
        url: 'https://create-next-app.com',
        siteName: 'Create Next App',
    }
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" data-theme='winter'>
            <GoogleAnalyticsScript />
            <body className={inter.className}>
                <AuthProvider>
                    <Navbar />
                    <main
                        className="p-5"
                    >
                        {children}
                    </main>
                </AuthProvider>
            </body>
        </html>
    )
}
